spring:
    kafka:
        consumer:
            auto-offset-reset: earliest
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
    level:
        root: INFO
        com.jpmc.midascore: DEBUG

general:
    kafka-topic: midas-transactions
