spring:
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver

    kafka:
        consumer:
            auto-offset-reset: earliest
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
    level:
        root: INFO
        com.jpmc.midascore: DEBUG

general:
    kafka-topic: midas-transactions
